version: '3'
services:
  #Postgres db container
  db:
    image: postgres
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  #Adminer container
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

    #Node app container
  node_app:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    volumes:
      - .:/app/
      - /app/node_modules
    command: npm run dev
